[versions]
# Android 8.0
minSdk = "26"
# Android 16.0
targetSdk = "36"
compileSdk = "36"

# JDK used by Gradle
java-toolchain = "21"

androidGradlePlugin = "9.0.0"

androidxAppcompat = "1.7.1"
androidxCoordinatorlayout = "1.3.0"
androidxDocumentfile = "1.1.0"
androidxFragment = "1.8.9"
androidxPreference = "1.2.1"
androidxRecyclerview = "1.4.0"

material = "1.13.0"
desugar = "2.1.5"

bouncycastle = "1.83"
eventbus = "3.3.1"
httpclient5 = "5.6"
junit = "4.13.2"
libsuperuser = "1.1.1"
logbackAndroid = "3.0.0"
slf4jApi = "2.0.17"
zxing = "1.9.8"

# Don't upgrade these any higher without migrating away from sshd-core 0.14
#noinspection NewerVersionAvailable
ftpserver = "1.1.4"
#noinspection NewerVersionAvailable
minaCore = "2.1.10"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
androidx-coordinatorlayout = { group = "androidx.coordinatorlayout", name = "coordinatorlayout", version.ref = "androidxCoordinatorlayout" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "androidxDocumentfile" }
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidxFragment" }
androidx-preference = { group = "androidx.preference", name = "preference-ktx", version.ref = "androidxPreference" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidxRecyclerview" }

google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
google-desugar = { group = "com.android.tools", name = "desugar_jdk_libs_nio", version.ref = "desugar" }

bouncycastle-bcprov = { group = "org.bouncycastle", name = "bcprov-jdk18on", version.ref = "bouncycastle" }
bouncycastle-bcpkix = { group = "org.bouncycastle", name = "bcpkix-jdk18on", version.ref = "bouncycastle" }
bouncycastle-bcutil = { group = "org.bouncycastle", name = "bcutil-jdk18on", version.ref = "bouncycastle" }

eventbus = { group = "org.greenrobot", name = "eventbus", version.ref = "eventbus" }
ftpserver-api = { group = "org.apache.ftpserver", name = "ftplet-api", version.ref = "ftpserver" }
ftpserver-core = { group = "org.apache.ftpserver", name = "ftpserver-core", version.ref = "ftpserver" }
httpclient5 = { group = "org.apache.httpcomponents.client5", name = "httpclient5", version.ref = "httpclient5" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
libsuperuser = { group = "eu.chainfire", name = "libsuperuser", version.ref = "libsuperuser" }
logback-android = { group = "com.github.tony19", name = "logback-android", version.ref = "logbackAndroid" }
mina-core = { group = "org.apache.mina", name = "mina-core", version.ref = "minaCore" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4jApi" }
zxing = { group = "me.dm7.barcodescanner", name = "zxing", version.ref = "zxing" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
java = { id = "java" }
maven-publish = { id = "maven-publish" }
